service: serverless-dynamodb

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: User
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:*"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
  create:
    handler: function/createUser.create
    events:
      - httpApi:
          path: /user/create
          method: post
