service: serverless-dynamodb

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    #    The following are a few example events you can configure
    #    NOTE: Please make sure to change your handler code to work with those events
    #    Check the event documentation for details
    events:
      - httpApi:
          path: /users/create
          method: get
